public with sharing class DHA_Student_Trigger_Handler {
    public static void onBeforeInsert(List<DHA_Student__c> newRecords) {
        return;
    }

	public static void onAfterInsert(List<DHA_Student__c> newRecords) {
        return;
    }

	public static void onBeforeUpdate(Map<Id, DHA_Student__c> newRecordMap, Map<Id, DHA_Student__c> oldRecordMap) {
        return;
	}

	public static void onAfterUpdate(Map<Id, DHA_Student__c> newRecordMap, Map<Id, DHA_Student__c> oldRecordMap) {
        return;
	}
}