public with sharing class DHA_Class_Assignment_Trigger_Handler {
    public static void onBeforeInsert(List<DHA_Class_Assignment__c> newRecords){
        return;
    }

    public static void onAfterInsert(List<DHA_Class_Assignment__c> newRecords){
        return;
    }

    public static void onBeforeUpdate(Map<Id, DHA_Class_Assignment__c> newRecordMap, Map<Id, DHA_Class_Assignment__c> oldRecordMap){
        return;
    }

    public static void onAfterUpdate(Map<Id, DHA_Class_Assignment__c> newRecordMap, Map<Id, DHA_Class_Assignment__c> oldRecordMap){
        return;
    }
}